name: legends_club_tower
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.6.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  audioplayers: ^3.0.1
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.3
  dotted_line: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^5.2.0
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/collection/
    # - assets/images/feedback/
    - assets/images/game_over/
    - assets/images/game/
    - assets/audio/
    - assets/json/country.json
